### ISSUE TITLE
Adding Slack notification to Jamf LAPS bookmark

### ISSUE THREAD

**Issue by keithemyers** [pro4tlzz/pro4tlzz.github.io#33]
Hi, the bookmark routine that you wrote is ingenious! It's the fastest and most elegant way to look up the Jamf LAPS password that I have found.

I'd like to add a slack notification with the username and computer name of the person that clicked the bookmark, date/time stamp, and the target machine name. Is that possible?

**Comment by pro4tlzz** [comment]
Hi, I'm glad you liked it. Thanks for using it.

Unfortunately I do not think a bookmarklet is the best way to handle what you need.

Essentially I could send a payload to a Slack webhook URL which contained that information but you'd need to press it each time and also customise the code to enter your webhook URL. This kind of thing better lives in a SIEM.

I won't be completing this at this point in time.

Thanks for your understanding.
